[package]
name = "bubbles_example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bubbles = { path = "../" }
env_logger = "0.11.6"
tokio = "1.43.0"

[[bin]]
name = "bubbles_example"
path = "src/main.rs"

